// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sm_center_TT.Services;

#nullable disable

namespace sm_center_TT.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("sm_center_TT.Models.Cabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cabinets");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Number = 100
                        },
                        new
                        {
                            Id = 1,
                            Number = 101
                        },
                        new
                        {
                            Id = 2,
                            Number = 102
                        },
                        new
                        {
                            Id = 3,
                            Number = 103
                        },
                        new
                        {
                            Id = 4,
                            Number = 104
                        },
                        new
                        {
                            Id = 5,
                            Number = 105
                        },
                        new
                        {
                            Id = 6,
                            Number = 108
                        },
                        new
                        {
                            Id = 7,
                            Number = 109
                        },
                        new
                        {
                            Id = 8,
                            Number = 110
                        },
                        new
                        {
                            Id = 9,
                            Number = 107
                        });
                });

            modelBuilder.Entity("sm_center_TT.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CabinetId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CabinetId = 5,
                            FullName = "Соколов Роман Кириллович",
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 2,
                            CabinetId = 6,
                            FullName = "Ермолаева Алиса Кирилловна",
                            PolyclinicId = 1,
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 3,
                            CabinetId = 7,
                            FullName = "Лосева Марьям Артемьевна",
                            PolyclinicId = 2,
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 4,
                            CabinetId = 8,
                            FullName = "Константинова Виктория Ильинична",
                            PolyclinicId = 3,
                            SpecializationId = 10
                        },
                        new
                        {
                            Id = 5,
                            CabinetId = 9,
                            FullName = "Антипов Даниил Савельевич",
                            PolyclinicId = 4,
                            SpecializationId = 9
                        },
                        new
                        {
                            Id = 6,
                            CabinetId = 10,
                            FullName = "Ермаков Владислав Ильич",
                            PolyclinicId = 5,
                            SpecializationId = 8
                        },
                        new
                        {
                            Id = 7,
                            CabinetId = 1,
                            FullName = "Колесникова Полина Егоровна",
                            PolyclinicId = 6,
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 8,
                            CabinetId = 2,
                            FullName = "Владимирова Аделина Львовна",
                            PolyclinicId = 7,
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 9,
                            CabinetId = 3,
                            FullName = "Гордеев Артемий Семёнович",
                            PolyclinicId = 8,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 10,
                            CabinetId = 4,
                            FullName = "Кириллова Виктория Владимировна",
                            PolyclinicId = 9,
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 11,
                            CabinetId = 5,
                            FullName = "Гришина София Матвеевна",
                            PolyclinicId = 10,
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 12,
                            CabinetId = 6,
                            FullName = "Ушаков Василий Александрович",
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 13,
                            CabinetId = 7,
                            FullName = "Соловьев Иван Маркович",
                            PolyclinicId = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 14,
                            CabinetId = 8,
                            FullName = "Пахомова Вероника Данииловна",
                            PolyclinicId = 2,
                            SpecializationId = 10
                        },
                        new
                        {
                            Id = 15,
                            CabinetId = 9,
                            FullName = "Зайцев Михаил Михайлович",
                            PolyclinicId = 3,
                            SpecializationId = 9
                        },
                        new
                        {
                            Id = 16,
                            CabinetId = 10,
                            FullName = "Сафонова Варвара Дмитриевна",
                            PolyclinicId = 4,
                            SpecializationId = 8
                        },
                        new
                        {
                            Id = 17,
                            CabinetId = 1,
                            FullName = "Титова Ариана Фёдоровна",
                            PolyclinicId = 5,
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 18,
                            CabinetId = 2,
                            FullName = "Маркова Ева Владимировна",
                            PolyclinicId = 6,
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 19,
                            CabinetId = 3,
                            FullName = "Абрамова Дарья Петровна",
                            PolyclinicId = 7,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 20,
                            CabinetId = 4,
                            FullName = "Степанова Алиса Григорьевна",
                            SpecializationId = 4
                        });
                });

            modelBuilder.Entity("sm_center_TT.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adderss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDay")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adderss = "Россия, г. Калининград, Космонавтов ул., д. 25 кв.18",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Павлов ",
                            IsMale = true,
                            MiddleName = "Ильич",
                            PolyclinicId = 1,
                            SecondName = "Максим "
                        },
                        new
                        {
                            Id = 2,
                            Adderss = "Россия, г. Петрозаводск, Ленинская ул., д. 21 кв.19",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Воронина ",
                            IsMale = false,
                            MiddleName = "Даниловна",
                            PolyclinicId = 2,
                            SecondName = "Ева "
                        },
                        new
                        {
                            Id = 3,
                            Adderss = "Россия, г. Подольск, Октябрьская ул., д. 21 кв.158",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Измайлова ",
                            IsMale = false,
                            MiddleName = "Олеговна",
                            PolyclinicId = 3,
                            SecondName = "Варвара "
                        },
                        new
                        {
                            Id = 4,
                            Adderss = "Россия, г. Черкесск, Лесной пер., д. 23 кв.58",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Поляков ",
                            IsMale = true,
                            MiddleName = "Даниилович",
                            PolyclinicId = 4,
                            SecondName = "Демьян "
                        },
                        new
                        {
                            Id = 5,
                            Adderss = "Россия, г. Ангарск, Ленина В.И.ул., д. 9 кв.84",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Соколова ",
                            IsMale = false,
                            MiddleName = "Владимировна",
                            PolyclinicId = 6,
                            SecondName = "Анна "
                        },
                        new
                        {
                            Id = 6,
                            Adderss = "Россия, г. Евпатория, Колхозный пер., д. 20 кв.59",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Горюнов ",
                            IsMale = true,
                            MiddleName = "Иванович",
                            PolyclinicId = 7,
                            SecondName = "Тимур "
                        },
                        new
                        {
                            Id = 7,
                            Adderss = "Россия, г. Кострома, ЯнкиКупалы ул., д. 2 кв.213",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Лебедев ",
                            IsMale = true,
                            MiddleName = "Тимофеевич",
                            PolyclinicId = 8,
                            SecondName = "Константин "
                        },
                        new
                        {
                            Id = 8,
                            Adderss = "Россия, г. Рубцовск, Мирная ул., д. 13 кв.24",
                            BirthDay = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Воронин ",
                            IsMale = true,
                            MiddleName = "Макарович",
                            PolyclinicId = 9,
                            SecondName = "Кирилл "
                        });
                });

            modelBuilder.Entity("sm_center_TT.Models.Polyclinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasComment("The URL of the blog");

                    b.HasKey("Id");

                    b.ToTable("Polyclinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            Number = 5
                        },
                        new
                        {
                            Id = 6,
                            Number = 6
                        },
                        new
                        {
                            Id = 7,
                            Number = 7
                        },
                        new
                        {
                            Id = 8,
                            Number = 8
                        },
                        new
                        {
                            Id = 9,
                            Number = 9
                        },
                        new
                        {
                            Id = 10,
                            Number = 10
                        });
                });

            modelBuilder.Entity("sm_center_TT.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Врач-кардиолог"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Врач-отоларинголог"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Врач-терапевт"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Врач-уролог"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Врач-акушер-гинеколог"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Врач-ревматолог"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Врач-офтальмолог"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Врач-дерматовенеролог"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Врач-психиатр"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Врач мануальной терапии"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
